name: Bug report
description: Nahlasit chybu
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Popis
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Kroky k reprodukci
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ocekavane chovani
    validations:
      required: true